import './globals.css'
import { Red_Hat_Display } from 'next/font/google';

const RedHatDisplay = Red_Hat_Display({ subsets: ["latin"], weight: ["400", "500","600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${RedHatDisplay.className} h-screen w-full`}>{children}</body>
    </html>
  )
}
